### ISSUE TITLE
TODO List

### ISSUE THREAD

**Issue by leisurelicht** [leisurelicht/LichtVim#8]
Recording what I will do in the next period of time

**Comment by leisurelicht** [comment]
- [ ] toggleterm 有点卡，找个可替换的插件
- [x] 追 lazyvim 的更新
- [ ] 看下 nvchad，SkCode 有什么可以借鉴的

**Comment by leisurelicht** [comment]
- [ ] 把 neoconfig 这个插件用起来
- [ ] lazy 页面打开时不许开启 nvim-tree
